### ISSUE TITLE
update apple root cert?

### ISSUE THREAD

**Issue by bukira** [parse-community/node-apn#49]
On March 29, 2021, token and certificate-based HTTP/2 connections to the Apple Push Notification service must incorporate the new root certificate (AAACertificateServices 5/12/2020) which replaces the old GeoTrust Global CA root certificate. To ensure a seamless transition and to avoid push notification delivery failures, verify that both the old and new root certificates for the HTTP/2 interface are included in the Trust Store of each of your notification servers before March 29. 

Will this be updated in the package?

**Comment by BorntraegerMarc** [comment]
Here is the link to the official Apple update: https://developer.apple.com/news/?id=7gx0a2lp

**Comment by TysonAndre** [comment]
node-apn uses the OS's certificate store. If you're running an out of date OS such as CentOS 6 or haven't updated ca-certificates (name varies based on OS) in 2020, you'll probably have issues. For a newer one such as Ubuntu 20.04 (any LTS?) or CentOS 7 you should be fine.


There's probably some facility in node's tls libraries to add additional certificates to allow when validating the certificate of the APNs server when connecting.

Node probably checks various paths (I haven't checked the source) - I'd guess it's similar to how golang does it?


```go
    "/etc/ssl/certs/ca-certificates.crt",                // Debian/Ubuntu/Gentoo etc.
    "/etc/pki/tls/certs/ca-bundle.crt",                  // Fedora/RHEL 6
    "/etc/ssl/ca-bundle.pem",                            // OpenSUSE
    "/etc/pki/tls/cacert.pem",                           // OpenELEC
    "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", // CentOS/RHEL 7
    "/etc/ssl/cert.pem",                                 // Alpine Linux
```

**Comment by ehubbell** [comment]
Going off @TysonAndre post above, if you check the `ca-certificates` package (https://packages.ubuntu.com/bionic/all/ca-certificates/filelist) which you can install via `apt-get install ca-certificates` you get the following certs in your `ca-certificates.crt` file mentioned above. 

```
/usr/share/ca-certificates/mozilla/Comodo_AAA_Services_root.crt
/usr/share/ca-certificates/mozilla/COMODO_RSA_Certification_Authority.crt
/usr/share/ca-certificates/mozilla/USERTrust_RSA_Certification_Authority.crt
```

I'm guessing those will fill Apple's new requirements.

**Comment by Dudarev2** [comment]
I have found that:
https://github.com/nodejs/node/blob/master/doc/guides/maintaining-root-certs.md
and that:
https://github.com/nodejs/node/blob/v8.x/src/node_root_certs.h

**Comment by junjie** [comment]
Is there any way to verify that the the AAA root certificate is present/used by node-apn before the rollover date of March 29?

**Comment by derN3rd** [comment]
> Is there any way to verify that the the AAA root certificate is present/used by node-apn before the rollover date of March 29?

You could try out this command: https://unix.stackexchange.com/a/97252

For me it shows `subject= /C=GB/ST=Greater Manchester/L=Salford/O=Comodo CA Limited/CN=AAA Certificate Services` which is the AAA root certificate afaik.

**Comment by junjie** [comment]
Thanks @derN3rd! I tried this on both my server and my Mac running Big Sur, which I expect would include the latest certificate, but I'm getting GeoTrust Global CA one running `openssl s_client -showcerts -connect api.push.apple.com:443`

![CleanShot 2021-02-16 at 09 26 23@2x](https://user-images.githubusercontent.com/524420/108007542-36d04e00-7039-11eb-83f5-317deb34488e.png)

Thinking about it I would expect that to be the case since the rollover date is Mar 29, and it'd probably not make sense for Apple to use the updated certificate now.

But I think the bigger issue here may be that Node.js, which this project depends upon, does not use the system certificate store, as @Dudarev2 has pointed out here: https://github.com/parse-community/node-apn/issues/49#issuecomment-778040411

I did make a small Node.js program to search through all the hardcoded certificates to find the AAA one, and I found it within my copy of Node installation. If you're interested:

```
var tls = require('tls'), fs = require('fs');

aaa = fs.readFileSync('AAACertificateServices.crt').toString();

allRootCertificates = tls.rootCertificates;
var i;
for (i = 0; i < allRootCertificates.length; i++) {
        if (allRootCertificates[i] === aaa) {
                console.log("Found AAA certificate at loop " + i);
                console.log(allRootCertificates[i]);
        }
}
console.log("Processed " + allRootCertificates.length + " certificates");

```

And AAACertificateServices.crt can be found via the link in Apple's email, or https://comodoca.my.salesforce.com/sfc/dist/version/download/?oid=00D1N000002Ljih&ids=0683l00000G9fLm&d=%2Fa%2F3l000000VbG0%2Fh70Hv.GWfGuD79pR_if0MtGjJFcUj.NRZS_RLqEyC_4&asPdf=false

**Comment by eladnava** [comment]
Nicely done, @junjie.

I'm running `Node v10` and `tls.rootCertificates` was only introduced in `Node v12+` so I can't run your code. 

However, I've just realized it's also possible to directly check Node's bundled root CA cert file for the signature of the Comodo AAA Services root:
https://github.com/nodejs/node/blob/v10.15.1/src/node_root_certs.h

Searching the file for `Comodo AAA Services root` will yield the exact certificate you have attached in Base64 encoded format.

You can plug in your Node.js version into the URL instead of `v1.0.0`, yet from what I've seen every single Node.js release has this root CA is present in all Node releases. 

Therefore, we can all safely assume that `node-apn` will continue functioning when Apple deploys the AAA certificate.

**Comment by derN3rd** [comment]
@eladnava I'm not sure if thats so easily done.
Apple stated in their mail

> On March 29, 2021, token and certificate-based HTTP/2 connections to the Apple Push Notification service must incorporate the new root certificate (AAACertificateServices 5/12/2020) which replaces the old GeoTrust Global CA root certificate
Which sounds to me that you need at least the AAA cert from December 2020, which is not in Node 10 or any build that was built before that date.

I have not enough knowledge about certs to tell if the _AAACertificateServices 5/12/2020_ is the same as _Comodo AAA Services root_ just renewed, but the fact that apple especially states the date of this cert sounds to me that there is a difference

**Comment by henrik** [comment]
Thank you so much for this helpful thread. I wrote up how we verified (I hope) our setup using what I learned here: https://stackoverflow.com/questions/66239455/how-to-verify-parse-running-on-heroku-supports-new-apple-push-notification-root/66239456

**Comment by BorntraegerMarc** [comment]
I would also dare to say that NodeJS v12.13.0+ supports the new `AAACertificateServices 5/12/2020` cert: https://github.com/nodejs/node/blob/v12.13.0/src/node_root_certs.h#L247

---

How I verified:

- Downloaded `AAACertificateServices 5/12/2020` cert from here: https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117cL
- Opened cert with text editor
- Copy / pasted first line from cert
- Searched for first line in NodeJS root certs and found it here: https://github.com/nodejs/node/blob/v12.13.0/src/node_root_certs.h#L247

**Comment by robsonalvesbh** [comment]
@BorntraegerMarc just to confirm, if my server application is running using NodeJS> v12 I don't need to take any action on my side?

**Comment by BorntraegerMarc** [comment]
@robsonalvesbh yes, if your application is running NodeJS v12.13.0+

**Comment by ArturV93** [comment]
If I am using *.p8 file for sending push notifications, is this issue affects me?
Apn version: 6.12.0
Node version: 12.13.0

**Comment by davimacedo** [comment]
It looks p8 will continue working. You need to make sure your apn version is using http/2 and it looks you are good with node 12.

**Comment by hb020** [comment]
as far as I can see, also node v11.15.0 is good as well. Probably also others.

**Comment by enoskov** [comment]
If you still feel uncertain whether your nodejs version embeds a new Root CA certificate, you may check nodejs binary using grep or hexedit and search for ASCII substring from a new cert. My nodejs 10.15.3 contains it:
![hexedit_node](https://user-images.githubusercontent.com/22984804/110667750-9efaf580-81db-11eb-89c6-eebffb18e9c3.png)

If it is still not enough for you, just add a config option for your node.js app to add 'ca' to apn.Provider's options and point to a desired Root CA cert. In case some unpleasant surprise will arise, you can always configure your app to enforse using AAACertificateServices.pem since March 29, 2021.

**Comment by eladnava** [comment]
@enoskov That's a really cool tip with grepping the `node` binary. Cheers!

**Comment by HardikDG** [comment]
My node version is : v12.18.4. 
I am having issue of InvalidProviderToken. Does it related to this root cert issue? 

Before 1-2 months it's working with P8 and TeamId

**Comment by TysonAndre** [comment]
> I am having issue of InvalidProviderToken. Does it related to this root cert issue?

No, I think you wouldn't even be able to connect to APNs to get this error if you had the wrong root certificate

https://github.com/node-apn/node-apn/issues/477 may be of use

Can this be closed? the certificate expired in march

**Comment by mtrezza** [comment]
I'm closing this as it does not seem to be a Parse node-apn issue.

- For help with Parse Platform we recommend our [community forum](https://community.parseplatform.org)
- For coding questions we recommend Stack Overflow using the [parse-platform](https://stackoverflow.com/questions/tagged/parse-platform) tag
- For network and server questions we recommend ServerFault using the [parse-server](https://serverfault.com/questions/tagged/parse-server) tag
