### ISSUE TITLE
iOS Device Does not receive Notification even though it is sent from node-apn

### ISSUE THREAD

**Issue by Vishal-sol** [parse-community/node-apn#59]
I just upgraded to the APNS Provider API from Legacy API, and I am sending the Push Notification from my Provider Server to an apple device. The `node-apn` Provider API gives a response like this:

````
0|app  | [iOS] Push Notification Transmitted.
0|app  |  {
0|app  |   "sent": [
0|app  |     {
0|app  |       "device": "c5d152f295a7c735c1d8ba837ac99f2caa86eb6e004e29b7a9455db25fd0f2bc"
0|app  |     }
0|app  |   ],
0|app  |   "failed": []
0|app  | }
````

But the device is not showing the push notification that was just sent to it. Is it APNS issue or am I missing something in the configuration of the Provider Server?

P.S. This functionality works with the older Legacy API, but the problem starts to occur when I update the Provider Server code to use the new Provider API.

**Comment by davimacedo** [comment]
Are you using a real device or an emulator?

**Comment by Vishal-sol** [comment]
> Are you using a real device or an emulator?

I am using a real device. 

I managed to figure out the issue though. With older API I was sending the notification payload like this:
```
let notification = new apn.Notification();
notification.payload = {
    aps: data
};
```

But with newer version, I had to send the notification like this:
```
let notification = new apn.Notification();
notification.aps = data;
```

But what I am wondering right now is why did the library and the APNS accept my 'badly constructed' payload as a valid payload?
Because that **old notification payload** used with the **new API** was **sent successfully** without any error by the library but it was **not showing up** on the device.

**Comment by davimacedo** [comment]
I am not sure but I can help to investigate. Would you mind to create a pr with a failing test case?

**Comment by samulla** [comment]
I am not able to receive the notifications as well from March 15th, is there some thing happened on the server side?
Could you please help.

**Comment by davimacedo** [comment]
Could you please give more context/details about your problem?

**Comment by joshuazmiller** [comment]
I had something similar happen to me today. Messages were being sent and received by the device and then suddenly they stopped working for maybe an hour. Then after an hour suddenly a bunch of messages appeared on the device. 

Note that I was trying to use the service a bit like a pubsub, so I was sending very frequent notifications (about 1 a second).

So my guess is Apple may sometimes have technical issues delivering the notifications (due to server load or who knows) and then plays catch-up. Or maybe there's some kind of rate limiting happening due to my high frequency use per device.

If there is no change in code on your end and Apple is returning a sent status but the device suddenly stops being notified that's my guess as to what's happening.

**Comment by rileyweber** [comment]
I think some of the delivery / delay issues being discussed may be caused by problems on the APNs side. Within the past couple of weeks we've started to see periods of elevated 500 status codes from apple. Typically, forcing our push service (a cluster of 8-10 servers) to re-establish new connections to APNs will resolve the error.

Note, we also will only see the error codes on 1-2 servers, which is what leads me to believe it's individual apns servers that encounter issues. And also likely why the restart of the service (forcing new connections) resolves the elevated error responses.

I figured I'd share our experiences since some are commenting on similar apns issues. Also note, I don't have any _real_ data (e.g. from Apple) to back this up. Purely speculative based on the symptoms and resolution

**Comment by TysonAndre** [comment]
> I had something similar happen to me today. Messages were being sent and received by the device and then suddenly they stopped working for maybe an hour. Then after an hour suddenly a bunch of messages appeared on the device.

I'm not sure if that's related - APNS will delay notifications unless they're marked as high priority until you unlock the device, so seeing a bunch of notifications once you unlock it might be the expected behavior.

> Note that I was trying to use the service a bit like a pubsub, so I was sending very frequent notifications (about 1 a second).

If you call setLogger with the unreleased changes on the development branch you would be able to see if there were any errors. Or use `DEBUG=apn` on any release to log everything.

> Edit: originally I wrote that we were getting 500s from APNs - this wasn't true. Internally, we default to 500 when we don't get any status code from apple, which I had originally forgotten about.

After adding the setLogger for errors, @rileyweber and I are seeing:

1. A lot of "Request timeout" on certain nodes to start with, sometimes recovering, occasionally lasting for hours or leading to a health check failure. The application is autoscaling to target 50% average cpu, though it can spike to higher levels when there are more targets or larger payloads. `Request timeout` can happen for hundreds of requests and often recovers on its own
2. After all of those errors, some "Session closed" errors, which may or may not be preceded by `apn error: Request error: Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM` (probably sent by APNs for opening too many streams) as well as the NGHTTP2_INTERNAL_ERROR (NGHTTP2_INTERNAL_ERROR is probably happening after the shutdown

```js
      const infoLogger = this.provider.client.logger;
      const errorLogger = (message) => { logger.error(`apn error: ${message}`); };  // logger is declared elsewhere
      errorLogger.enabled = true; // required to emulate npm debug module's interface

      this.provider.client.setLogger(infoLogger, errorLogger);
```

-----

Mitigations being considered include sending smaller batches to this service to call node-apn with, lowering the cpu usage target to make timeouts or other edge cases less likely, etc

**Comment by mtrezza** [comment]
I'm closing this as it does not seem to be a Parse node-apn issue.

- For help with Parse Platform we recommend our [community forum](https://community.parseplatform.org)
- For coding questions we recommend Stack Overflow using the [parse-platform](https://stackoverflow.com/questions/tagged/parse-platform) tag
- For network and server questions we recommend ServerFault using the [parse-server](https://serverfault.com/questions/tagged/parse-server) tag
